version: "3.7"
services:

  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports: 
      - 8080:8080
    environment: 
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=password
      - HASURA_GRAPHQL_AUTH_HOOK=http://hasura-actions:3000/auth
      - HASURA_ACTIONS_URL=http://hasura-actions:3000
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
    depends_on:
      - "postgres"
    restart: always

  hasura-actions:
    build:
      context: ./hasura/actions
    volumes:
      - /home/node/app/node_modules
      - ./hasura/actions:/home/node/app
    restart: always

  postgres:
    image: postgres:13
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data: